-- Clear existing reading plans and insert 100 new ones
-- First, delete all existing reading plans
DELETE FROM reading_plans;

-- Now insert 100 comprehensive reading plans
INSERT INTO reading_plans (
  id,
  title,
  description,
  duration,
  difficulty,
  user_id,
  is_public,
  created_at,
  updated_at
) VALUES 
-- New Testament Reading Plans (1-30)
(
  gen_random_uuid(),
  'Gospel of Matthew in 28 Days',
  'Read through the entire Gospel of Matthew in one month, focusing on the life, teachings, death, and resurrection of Jesus Christ.',
  28,
  'beginner',
  NULL,
  true,
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  'Gospel of Mark in 16 Days',
  'A fast-paced journey through Mark''s Gospel, perfect for understanding the quick action and miracles of Jesus.',
  16,
  'beginner',
  NULL,
  true,
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  'Gospel of Luke in 24 Days',
  'Explore Luke''s detailed account of Jesus'' life, with special attention to His compassion for the marginalized.',
  24,
  'intermediate',
  NULL,
  true,
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  'Gospel of John in 21 Days',
  'Deep dive into John''s spiritual and theological portrait of Jesus as the Son of God.',
  21,
  'intermediate',
  NULL,
  true,
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  'Acts of the Apostles in 28 Days',
  'Follow the early church''s journey from Jerusalem to Rome, empowered by the Holy Spirit.',
  28,
  'intermediate',
  NULL,
  true,
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  'Romans in 16 Days',
  'Study Paul''s masterpiece of Christian theology, understanding justification by faith.',
  16,
  'advanced',
  NULL,
  true,
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  '1 Corinthians in 16 Days',
  'Learn about Christian unity, spiritual gifts, and the resurrection from Paul''s letter to the Corinthians.',
  16,
  'intermediate',
  NULL,
  true,
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  '2 Corinthians in 13 Days',
  'Discover God''s strength in human weakness and the ministry of reconciliation.',
  13,
  'intermediate',
  NULL,
  true,
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  'Galatians in 6 Days',
  'Understand Christian freedom and life in the Spirit through this powerful letter.',
  6,
  'beginner',
  NULL,
  true,
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  'Ephesians in 6 Days',
  'Explore the riches of God''s grace and the armor of God for spiritual warfare.',
  6,
  'intermediate',
  NULL,
  true,
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  'Philippians in 4 Days',
  'Experience the joy of Christian living through Paul''s letter of rejoicing.',
  4,
  'beginner',
  NULL,
  true,
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  'Colossians in 4 Days',
  'Discover the supremacy of Christ and the new life in Him.',
  4,
  'intermediate',
  NULL,
  true,
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  '1 & 2 Thessalonians in 8 Days',
  'Learn about Christ''s return, holy living, and standing firm in the faith.',
  8,
  'beginner',
  NULL,
  true,
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  '1 & 2 Timothy in 10 Days',
  'Study pastoral leadership, sound doctrine, and fighting the good fight of faith.',
  10,
  'intermediate',
  NULL,
  true,
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  'Titus and Philemon in 4 Days',
  'Explore church leadership and Christian fellowship through these short letters.',
  4,
  'beginner',
  NULL,
  true,
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  'Hebrews in 13 Days',
  'Understand Christ as our High Priest and the superiority of the new covenant.',
  13,
  'advanced',
  NULL,
  true,
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  'James in 5 Days',
  'Practical wisdom for living out your faith through works and perseverance.',
  5,
  'beginner',
  NULL,
  true,
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  '1 & 2 Peter in 8 Days',
  'Learn about suffering for Christ, spiritual growth, and false teachings.',
  8,
  'intermediate',
  NULL,
  true,
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  '1, 2, & 3 John in 7 Days',
  'Explore love, truth, and walking in the light through John''s letters.',
  7,
  'beginner',
  NULL,
  true,
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  'Jude and Revelation in 22 Days',
  'Contend for the faith and explore the end times through these prophetic books.',
  22,
  'advanced',
  NULL,
  true,
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  'Parables of Jesus in 14 Days',
  'Study Jesus'' teachings through His powerful parables about the Kingdom of God.',
  14,
  'intermediate',
  NULL,
  true,
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  'Miracles of Jesus in 14 Days',
  'Witness the power and compassion of Christ through His miraculous works.',
  14,
  'beginner',
  NULL,
  true,
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  'Sermon on the Mount in 7 Days',
  'Deep dive into Jesus'' most famous teaching about Kingdom living.',
  7,
  'intermediate',
  NULL,
  true,
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  'Upper Room Discourse in 4 Days',
  'Study Jesus'' intimate teachings to His disciples on the night before His crucifixion.',
  4,
  'intermediate',
  NULL,
  true,
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  'Resurrection Appearances in 7 Days',
  'Explore the post-resurrection appearances of Jesus and their significance.',
  7,
  'beginner',
  NULL,
  true,
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  'Great Commission in 7 Days',
  'Study Jesus'' command to make disciples of all nations.',
  7,
  'beginner',
  NULL,
  true,
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  'Fruit of the Spirit in 9 Days',
  'Develop Christ-like character through studying the fruit of the Spirit.',
  9,
  'beginner',
  NULL,
  true,
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  'Armor of God in 7 Days',
  'Prepare for spiritual warfare by understanding God''s protective armor.',
  7,
  'intermediate',
  NULL,
  true,
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  'Beatitudes in 9 Days',
  'Explore the blessings of Kingdom living through Jesus'' opening statements.',
  9,
  'beginner',
  NULL,
  true,
  NOW(),
  NOW()
),

-- Old Testament Reading Plans (31-60)
(
  gen_random_uuid(),
  'Genesis in 50 Days',
  'Journey through creation, the patriarchs, and God''s covenant promises.',
  50,
  'intermediate',
  NULL,
  true,
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  'Exodus in 40 Days',
  'Experience the deliverance from Egypt and the giving of the Law at Sinai.',
  40,
  'intermediate',
  NULL,
  true,
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  'Leviticus in 27 Days',
  'Understand holiness, worship, and sacrifice through the Law of Moses.',
  27,
  'advanced',
  NULL,
  true,
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  'Numbers in 36 Days',
  'Follow Israel''s wilderness journey and learn from their victories and failures.',
  36,
  'intermediate',
  NULL,
  true,
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  'Deuteronomy in 34 Days',
  'Review God''s law and prepare to enter the Promised Land.',
  34,
  'intermediate',
  NULL,
  true,
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  'Joshua in 24 Days',
  'Conquer the Promised Land through faith and obedience.',
  24,
  'beginner',
  NULL,
  true,
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  'Judges in 21 Days',
  'Learn from Israel''s cycle of sin, judgment, and deliverance.',
  21,
  'intermediate',
  NULL,
  true,
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  'Ruth in 4 Days',
  'Discover God''s redemptive love through this beautiful story of loyalty and faith.',
  4,
  'beginner',
  NULL,
  true,
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  '1 Samuel in 31 Days',
  'From Samuel to Saul, understand God''s leadership and Israel''s first king.',
  31,
  'intermediate',
  NULL,
  true,
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  '2 Samuel in 24 Days',
  'Follow David''s reign as king, his triumphs, and his failures.',
  24,
  'intermediate',
  NULL,
  true,
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  '1 Kings in 22 Days',
  'From Solomon''s wisdom to the division of the kingdom.',
  22,
  'intermediate',
  NULL,
  true,
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  '2 Kings in 25 Days',
  'Witness the fall of Israel and Judah through their disobedience.',
  25,
  'intermediate',
  NULL,
  true,
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  '1 Chronicles in 29 Days',
  'Review Israel''s history with focus on David''s reign and temple preparation.',
  29,
  'intermediate',
  NULL,
  true,
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  '2 Chronicles in 36 Days',
  'See Judah''s kings and the importance of temple worship.',
  36,
  'intermediate',
  NULL,
  true,
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  'Ezra in 10 Days',
  'Return from exile and rebuild the temple and community.',
  10,
  'beginner',
  NULL,
  true,
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  'Nehemiah in 13 Days',
  'Rebuild Jerusalem''s walls and restore the people of God.',
  13,
  'beginner',
  NULL,
  true,
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  'Esther in 10 Days',
  'See God''s providence in saving His people through Queen Esther.',
  10,
  'beginner',
  NULL,
  true,
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  'Job in 42 Days',
  'Explore suffering, faith, and God''s sovereignty in this profound book.',
  42,
  'advanced',
  NULL,
  true,
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  'Psalms in 150 Days',
  'Journey through the entire prayer book of Israel, one psalm per day.',
  150,
  'beginner',
  NULL,
  true,
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  'Proverbs in 31 Days',
  'Gain daily wisdom for practical living through God''s proverbs.',
  31,
  'beginner',
  NULL,
  true,
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  'Ecclesiastes in 12 Days',
  'Find meaning in life through Solomon''s search for purpose.',
  12,
  'intermediate',
  NULL,
  true,
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  'Song of Solomon in 8 Days',
  'Explore God''s design for love and marriage through this poetic book.',
  8,
  'intermediate',
  NULL,
  true,
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  'Isaiah in 66 Days',
  'Experience the prophet''s vision of God''s holiness and the coming Messiah.',
  66,
  'advanced',
  NULL,
  true,
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  'Jeremiah in 52 Days',
  'Weep with the prophet over Judah''s sin and find hope in God''s promises.',
  52,
  'advanced',
  NULL,
  true,
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  'Lamentations in 5 Days',
  'Process grief and find hope in God''s mercy through these laments.',
  5,
  'intermediate',
  NULL,
  true,
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  'Ezekiel in 48 Days',
  'See God''s glory and restoration through the prophet''s visions.',
  48,
  'advanced',
  NULL,
  true,
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  'Daniel in 12 Days',
  'Stand firm in faith through persecution and understand end-time prophecies.',
  12,
  'intermediate',
  NULL,
  true,
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  'Hosea in 14 Days',
  'Understand God''s unfailing love through the prophet''s marriage story.',
  14,
  'intermediate',
  NULL,
  true,
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  'Joel in 3 Days',
  'Experience the outpouring of the Spirit and the day of the Lord.',
  3,
  'beginner',
  NULL,
  true,
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  'Amos in 9 Days',
  'Hear God''s call for justice and righteousness for the poor and oppressed.',
  9,
  'intermediate',
  NULL,
  true,
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  'Obadiah in 1 Day',
  'Learn about pride, humility, and God''s justice in this brief prophecy.',
  1,
  'beginner',
  NULL,
  true,
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  'Jonah in 4 Days',
  'Discover God''s mercy for all people through the reluctant prophet.',
  4,
  'beginner',
  NULL,
  true,
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  'Micah in 7 Days',
  'Act justly, love mercy, and walk humbly with your God.',
  7,
  'intermediate',
  NULL,
  true,
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  'Nahum in 3 Days',
  'See God''s judgment on Nineveh and His protection of His people.',
  3,
  'beginner',
  NULL,
  true,
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  'Habakkuk in 3 Days',
  'Learn to trust God in difficult times and live by faith.',
  3,
  'intermediate',
  NULL,
  true,
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  'Zephaniah in 3 Days',
  'Find hope in God''s restoration and salvation for the faithful.',
  3,
  'beginner',
  NULL,
  true,
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  'Haggai in 2 Days',
  'Prioritize God''s house and experience His blessing and presence.',
  2,
  'beginner',
  NULL,
  true,
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  'Zechariah in 14 Days',
  'Explore messianic prophecies and visions of Israel''s restoration.',
  14,
  'advanced',
  NULL,
  true,
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  'Malachi in 4 Days',
  'Prepare for the Lord''s coming through this final prophetic message.',
  4,
  'intermediate',
  NULL,
  true,
  NOW(),
  NOW()
),

-- Thematic Reading Plans (61-80)
(
  gen_random_uuid(),
  '21 Days of Prayer',
  'Develop a consistent prayer life and deepen your relationship with God.',
  21,
  'beginner',
  NULL,
  true,
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  '30 Days of Gratitude',
  'Cultivate a thankful heart through daily scripture and reflection.',
  30,
  'beginner',
  NULL,
  true,
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  '40 Days of Faith',
  'Strengthen your faith through stories of God''s faithfulness.',
  40,
  'intermediate',
  NULL,
  true,
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  '7 Days of Forgiveness',
  'Experience the freedom of forgiving others and receiving God''s forgiveness.',
  7,
  'beginner',
  NULL,
  true,
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  '14 Days of Wisdom',
  'Gain practical wisdom for life''s decisions through Proverbs and other wisdom literature.',
  14,
  'intermediate',
  NULL,
  true,
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  '21 Days of Spiritual Warfare',
  'Understand the battle against spiritual forces and God''s victory.',
  21,
  'advanced',
  NULL,
  true,
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  '30 Days of God''s Love',
  'Immerse yourself in the depth and breadth of God''s love.',
  30,
  'beginner',
  NULL,
  true,
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  '10 Days of Repentance',
  'Experience true repentance and restoration through God''s grace.',
  10,
  'intermediate',
  NULL,
  true,
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  '28 Days of Hope',
  'Find hope in God''s promises through difficult circumstances.',
  28,
  'beginner',
  NULL,
  true,
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  '15 Days of Courage',
  'Be inspired to stand firm in faith through stories of biblical courage.',
  15,
  'intermediate',
  NULL,
  true,
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  '20 Days of Joy',
  'Discover the secret of true joy that transcends circumstances.',
  20,
  'beginner',
  NULL,
  true,
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  '12 Days of Peace',
  'Experience God''s peace that passes all understanding.',
  12,
  'beginner',
  NULL,
  true,
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  '25 Days of Christmas',
  'Prepare your heart for Christmas through the prophecies and story of Jesus'' birth.',
  25,
  'beginner',
  NULL,
  true,
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  '40 Days of Lent',
  'Reflect on Christ''s sacrifice and prepare for Easter.',
  40,
  'intermediate',
  NULL,
  true,
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  '50 Days of Easter',
  'Celebrate the resurrection and its implications for daily life.',
  50,
  'intermediate',
  NULL,
  true,
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  '30 Days of Marriage',
  'Strengthen your marriage through biblical principles and examples.',
  30,
  'intermediate',
  NULL,
  true,
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  '21 Days of Parenting',
  'Find biblical wisdom for raising children in the Lord.',
  21,
  'intermediate',
  NULL,
  true,
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  '14 Days of Singleness',
  'Embrace the gift of singleness and serve God with your whole heart.',
  14,
  'beginner',
  NULL,
  true,
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  '30 Days of Work',
  'Find purpose and meaning in your daily work through biblical principles.',
  30,
  'intermediate',
  NULL,
  true,
  NOW(),
  NOW()
),

-- Character Studies (81-100)
(
  gen_random_uuid(),
  '30 Days with Abraham',
  'Learn faith and obedience from the father of our faith.',
  30,
  'intermediate',
  NULL,
  true,
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  '40 Days with Moses',
  'Follow the life of the great leader and lawgiver of Israel.',
  40,
  'intermediate',
  NULL,
  true,
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  '30 Days with David',
  'Experience the heart of a shepherd, warrior, and king after God''s own heart.',
  30,
  'intermediate',
  NULL,
  true,
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  '21 Days with Elijah',
  'Stand for God''s truth through the life of the powerful prophet.',
  21,
  'intermediate',
  NULL,
  true,
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  '30 Days with Isaiah',
  'See the glory of God and the coming Messiah through the prophet''s eyes.',
  30,
  'advanced',
  NULL,
  true,
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  '30 Days with Jeremiah',
  'Weep with the weeping prophet and find hope in God''s promises.',
  30,
  'advanced',
  NULL,
  true,
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  '30 Days with Daniel',
  'Stand firm in faith in a hostile culture through Daniel''s example.',
  30,
  'intermediate',
  NULL,
  true,
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  '30 Days with Peter',
  'Transform from impulsive fisherman to bold apostle through Peter''s journey.',
  30,
  'intermediate',
  NULL,
  true,
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  '30 Days with Paul',
  'Understand the apostle to the Gentiles and his missionary journeys.',
  30,
  'advanced',
  NULL,
  true,
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  '21 Days with Mary',
  'Learn humility and devotion from the mother of Jesus.',
  21,
  'beginner',
  NULL,
  true,
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  '30 Days with Joseph',
  'Trust God''s providence through betrayal, prison, and promotion.',
  30,
  'intermediate',
  NULL,
  true,
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  '21 Days with Ruth',
  'Experience loyalty and redemption through this remarkable woman.',
  21,
  'beginner',
  NULL,
  true,
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  '30 Days with Esther',
  'Find courage to stand for your people in times of crisis.',
  30,
  'intermediate',
  NULL,
  true,
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  '21 Days with Nehemiah',
  'Lead with prayer, vision, and determination through Nehemiah''s example.',
  21,
  'intermediate',
  NULL,
  true,
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  '30 Days with John the Baptist',
  'Prepare the way of the Lord through the life of the forerunner.',
  30,
  'intermediate',
  NULL,
  true,
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  '21 Days with Mary Magdalene',
  'Experience transformation and devotion through the first witness of the resurrection.',
  21,
  'beginner',
  NULL,
  true,
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  '30 Days with Timothy',
  'Learn faithful ministry and leadership from Paul''s spiritual son.',
  30,
  'intermediate',
  NULL,
  true,
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  '21 Days with Lydia',
  'Be inspired by hospitality and leadership in the early church.',
  21,
  'beginner',
  NULL,
  true,
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  '30 Days with Barnabas',
  'Practice encouragement and support in the body of Christ.',
  30,
  'beginner',
  NULL,
  true,
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  '21 Days with Silas',
  'Learn faithful service and suffering for the gospel.',
  21,
  'intermediate',
  NULL,
  true,
  NOW(),
  NOW()
);
