var R=require("../../../chunks/[turbopack]_runtime.js")("server/app/api/reading-plans/route.js")
R.c("server/chunks/node_modules_next_7af6257f._.js")
R.c("server/chunks/node_modules_@supabase_realtime-js_dist_module_306ac729._.js")
R.c("server/chunks/node_modules_@supabase_storage-js_dist_module_473cf4b8._.js")
R.c("server/chunks/node_modules_@supabase_auth-js_dist_module_d4605ced._.js")
R.c("server/chunks/node_modules_861fd42b._.js")
R.c("server/chunks/[root-of-the-server]__2a206854._.js")
R.c("server/chunks/_next-internal_server_app_api_reading-plans_route_actions_977ca14a.js")
R.m("[project]/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/src/app/api/reading-plans/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)")
module.exports=R.m("[project]/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/src/app/api/reading-plans/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)").exports
